events {}

http {

    upstream backend {
        server blue-app:8000;
        # Jenkins will switch this to green-app:8000
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://backend/health;
        }
    }
}
